
import conectar.conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Martin Fuentes
 */
public class Formulario_Calificacion_Estudiante extends javax.swing.JFrame {

    String Usuario;
    String[][] ConsultaActual;
    int i = 0;

    /**
     * Creates new form Formulario_Calificacion_Estudiante
     */
    public Formulario_Calificacion_Estudiante(String Usuario) {
        initComponents();

        this.Usuario = Usuario;

        this.setLocationRelativeTo(null);
        actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaForm = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 242, 227));
        jPanel1.setLayout(null);

        tablaForm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tablaForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Calificación", "Materia", "Nivel"
            }
        ));
        tablaForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaFormMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaForm);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 533, 280);

        jButton2.setBackground(new java.awt.Color(49, 73, 109));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 0, 130, 40);

        jButton1.setBackground(new java.awt.Color(49, 73, 109));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprobar.png"))); // NOI18N
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 420, 130, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/espumoso.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(6, 472, 24, 24);

        jLabel1.setBackground(new java.awt.Color(49, 73, 109));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 73, 109));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario Calificación Estudiante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 50, 380, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/espumoso.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(538, 0, 24, 24);

        jButton3.setBackground(new java.awt.Color(49, 73, 109));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(240, 420, 140, 40);

        jButton4.setBackground(new java.awt.Color(49, 73, 109));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardararchivo .png"))); // NOI18N
        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(400, 420, 130, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevinform.jpg"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 570, 500);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
 conectar conecta = new conectar();
        Connection con = conecta.getConexion();
        Statement pst;
        if (tablaForm.getSelectedRow() != -1) {
            int filaseleccionada = tablaForm.getSelectedRow();
            int id = Integer.parseInt(ConsultaActual[filaseleccionada][5]);
            String sql="DELETE FROM Calificacion_Materia Where id_Calificacion_Materia='"+id+"'";
            try {
                pst=con.createStatement();
                pst.executeUpdate(sql);
                i=0;
                actualizar();
                JOptionPane.showMessageDialog(null, "Se ha eliminado exitosamente") ;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error de conexión:" + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       new Menu_Estudiante(Usuario).setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed
    private DefaultTableModel modelo;
    private void tablaFormMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFormMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tablaFormMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        conectar conecta = new conectar();
        Connection con = conecta.getConexion();
        Statement pst;

        for (int e = 0; e <= i - 1; e++) {
            for (int j = 0; j <= 4; j++) {
                String sql;
                String valor = modelo.getValueAt(e, j).toString();
                if (!valor.equals(ConsultaActual)) {
                    switch (j) {
                        case 0:
                            sql = "UPDATE Calificacion_Materia SET Cedula_Estudiante='" + valor + "' WHERE id_Calificacion_Materia='" + ConsultaActual[e][5] + "'";

                            try {
                                pst = con.createStatement();
                                pst.executeUpdate(sql);
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, "Error de conexión:" + ex.getMessage());

                            }
                            break;
                        case 1:
                            sql = "UPDATE Calificacion_Materia SET Nombre='" + valor + "' WHERE id_Calificacion_Materia='" + ConsultaActual[e][5] + "'";

                            try {
                                pst = con.createStatement();
                                pst.executeUpdate(sql);
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, "Error de conexión:" + ex.getMessage());

                            }
                            break;
                        case 2:
                            sql = "UPDATE Calificacion_Materia SET Calificacion='" + Double.parseDouble(valor) + "' WHERE id_Calificacion_Materia='" + ConsultaActual[e][5] + "'";

                            try {
                                pst = con.createStatement();
                                pst.executeUpdate(sql);
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, "Error de conexión:" + ex.getMessage());

                            }
                            break;
                        case 3:
                            sql = "UPDATE Calificacion_Materia SET Materia='" + valor + "' WHERE id_Calificacion_Materia='" + ConsultaActual[e][5] + "'";

                            try {
                                pst = con.createStatement();
                                pst.executeUpdate(sql);
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, "Error de conexión:" + ex.getMessage());

                            }
                            break;
                        case 4:
                            sql = "UPDATE Calificacion_Materia SET Nivel='" + valor + "' WHERE id_Calificacion_Materia='" + ConsultaActual[e][5] + "'";

                            try {
                                pst = con.createStatement();
                                pst.executeUpdate(sql);
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, "Error de conexión:" + ex.getMessage());

                            }
                            break;
                    }

                }
            }

        }
        i = 0;
        actualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ActualizarCalificación(Usuario).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    public void actualizar() {
        String[][] valores = new String[5][1000];
        conectar conecta = new conectar();
        Connection con = conecta.getConexion();
        String sql = "Select Cedula_Estudiante,Nombre,Materia,Calificacion,Nivel,id_Calificacion_Materia from Calificacion_Materia Where Cedula_Usuario = '" + Usuario + "' ORDER BY Nivel ASC";
        modelo = new DefaultTableModel();

        modelo.addColumn("Cedula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Nivel");
        modelo.addColumn("Calificación");
        modelo.addColumn("Materia");
        try {
            Statement pst = con.createStatement();
            ResultSet rs = pst.executeQuery(sql);
            String ced, nom, mat, niv;
            double cali;
            int id;

            while (rs.next()) {
                ced = rs.getString("Cedula_Estudiante");
                nom = rs.getString("Nombre");
                cali = rs.getDouble("Calificacion");
                mat = rs.getString("Materia");
                niv = rs.getString("Nivel");
                id = rs.getInt("id_Calificacion_Materia");
                String cali2 = cali + "";

                modelo.addRow(new Object[]{ced, nom, cali2, mat, niv});
                valores[i][0] = ced;
                valores[i][1] = nom;
                valores[i][2] = cali2;
                valores[i][3] = mat;
                valores[i][4] = niv;
                valores[i][5] = id + "";
                i++;
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error de conexión:" + e.getMessage());

        }
        ConsultaActual = valores;
        tablaForm.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Calificacion_Estudiante.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Calificacion_Estudiante.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Calificacion_Estudiante.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Calificacion_Estudiante.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar_Sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaForm;
    // End of variables declaration//GEN-END:variables
}
